In [88]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [91]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder , MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [110]:
df = pd.read_csv('/content/train.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [111]:
df.drop(columns = ["PassengerId" , "Name" , "Ticket","Cabin"] , inplace = True)

In [112]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [113]:
X_train , X_test  , y_train ,y_test = train_test_split(df.drop("Survived" , axis = 1),
                                                       df["Survived"],
                                                       test_size = 0.2,
                                                       random_state = 0)

In [114]:
X_train.head()

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
140       3  female   NaN      0      2  15.2458        C
439       2    male  31.0      0      0  10.5000        S
817       2    male  31.0      1      1  37.0042        C
378       3    male  20.0      0      0   4.0125        C
491       3    male  21.0      0      0   7.2500        S

In [115]:
y_train.head()

140    0
439    0
817    0
378    0
491    0
Name: Survived, dtype: int64

In [116]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [117]:
## Applying Simple Imputer
si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy= "most_frequent")

X_train_age = si_age.fit_transform(X_train[["Age"]])
X_train_embarked = si_embarked.fit_transform(X_train[["Embarked"]])

X_test_age = si_age.transform(X_test[["Age"]])
X_test_embarked = si_embarked.transform(X_test[["Embarked"]])

In [118]:
## One Hot Encoding  Sex and Embarked
ohe_sex = OneHotEncoder(sparse_output = False , handle_unknown = "ignore")
ohe_embarked = OneHotEncoder(sparse_output = False ,  handle_unknown = "ignore")

X_train_sex = ohe_sex.fit_transform(X_train[["Sex"]])
X_train_embarked = ohe_embarked.fit_transform(X_train_embarked)

X_test_sex = ohe_sex.transform(X_test[["Sex"]])
X_test_embarked = ohe_embarked.transform(X_test_embarked)

In [119]:
X_train_embarked

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [120]:
X_train_rem = X_train.drop(columns = ["Sex","Age","Embarked"])
X_test_rem = X_test.drop(columns = ["Sex","Age","Embarked"])

In [122]:
X_train_transformed = np.concatenate((X_train_rem , X_train_age  , X_train_sex , X_train_embarked) , axis = 1)
X_test_transformed = np.concatenate((X_test_rem , X_test_age  , X_test_sex , X_test_embarked) , axis = 1)

In [127]:
X_train_transformed.shape

(712, 10)

In [128]:
cls = DecisionTreeClassifier()
cls.fit(X_train_transformed , y_train)

DecisionTreeClassifier()

In [129]:
y_pred = cls.predict(X_test_transformed)

In [131]:
y_pred

array([0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1])

In [130]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test , y_pred)

0.770949720670391

In [134]:
import os
os.mkdir("models")

In [135]:
import pickle

pickle.dump(ohe_sex , open("models/ohe_sex.pkl" , "wb"))
pickle.dump(ohe_embarked , open("models/ohe_embarked.pkl","wb"))
pickle.dump(cls , open("models/cls.pkl", "wb"))

# **Loading Models for Testing **

In [136]:
ohe_sex = pickle.load(open("models/ohe_sex.pkl","rb"))
ohe_embarked = pickle.load(open("models/ohe_embarked.pkl","rb"))
cls = pickle.load(open("models/cls.pkl","rb"))

In [137]:
# User inputs
test_input = np.array([2 , "male" , 31.0 , 0 , 0 , 10.5 , "S"] , dtype = object).reshape(1,7)
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [144]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(-1,1))
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(-1,1))

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [145]:
test_input_age = test_input[:,2].reshape(-1,1)

In [146]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age , test_input_sex , test_input_embarked),axis = 1)

In [147]:
test_input_transformed.shape

(1, 10)

In [148]:
cls.predict(test_input_transformed)

array([0])