In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import sklearn
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.datasets import load_iris

iris = load_iris()


In [3]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df["flower"] = iris.target
df["flower"] = df["flower"].apply(lambda x : iris.target_names[x])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [4]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.3)

In [5]:
from sklearn.svm import SVC

model = SVC(kernel="rbf",C=30,gamma="auto")
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.9555555555555556

In [6]:
from sklearn.model_selection import cross_val_score

cross_val_score(SVC(kernel="linear",C=10,gamma="auto"),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [7]:
cross_val_score(SVC(kernel="rbf",C=10,gamma="auto"),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [8]:
cross_val_score(SVC(kernel="rbf",C=20,gamma="auto"),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [9]:
kernel = ["linear","rbf"]
C = [1,10,20]
avg_score = {}

for kval in kernel:
  for cval in C:
    cv_score = cross_val_score(SVC(kernel=kval,C=cval,gamma="auto"),iris.data,iris.target,cv=5)
    avg_score[kval+"_"+str(cval)] = np.average(cv_score)

avg_score

{'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668}

In [10]:
#### GridSearchCV : It do same things as above
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(SVC(gamma="auto"),{
    "C" : [1,10,20],
    "kernel" : ["rbf","linear"]
},cv=5,return_train_score= False)

clf.fit(iris.data,iris.target)
clf.cv_results_

{'mean_fit_time': array([0.01446719, 0.00276847, 0.00202146, 0.00180182, 0.00360122,
        0.00537806]),
 'std_fit_time': array([0.01683599, 0.00127239, 0.00029729, 0.00015417, 0.00091324,
        0.00242709]),
 'mean_score_time': array([0.00576286, 0.00136323, 0.00142851, 0.00126147, 0.00293722,
        0.00372992]),
 'std_score_time': array([0.00314056, 0.00025993, 0.00013569, 0.00014268, 0.00067556,
        0.0021997 ]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],
 'split0_test_score': ar

In [11]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0       0.014467      0.016836         0.005763        0.003141        1   
1       0.002768      0.001272         0.001363        0.000260        1   
2       0.002021      0.000297         0.001429        0.000136       10   
3       0.001802      0.000154         0.001261        0.000143       10   
4       0.003601      0.000913         0.002937        0.000676       20   
5       0.005378      0.002427         0.003730        0.002200       20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [12]:
df[["param_C","param_kernel","mean_test_score"]]

param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667

In [13]:
clf.best_score_

0.9800000000000001

In [14]:
clf.best_estimator_

SVC(C=1, gamma='auto')

In [15]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [16]:
#### RandomizedSearchCV
#### GridSearchCV : It do same things as above
from sklearn.model_selection import RandomizedSearchCV

rs = RandomizedSearchCV(SVC(gamma="auto"),{
    "C" : [1,10,20],
    "kernel" : ["rbf","linear"]
},cv=5,
return_train_score= False,
                        n_iter=2)

rs.fit(iris.data,iris.target)
df = pd.DataFrame(rs.cv_results_)
df[["param_C","param_kernel","mean_test_score"]]




param_C param_kernel  mean_test_score
0       20       linear         0.966667
1       10       linear         0.973333

# Chosing Best Model

In [27]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression


In [28]:
model_params = {
    "svm" : {
        "model" : SVC(gamma="auto"),
        "params" : {
            "C" : [1,10,20],
            "kernel" : ["rbf" , "linear"]
        }
    },
    "random_forest" : {
        "model" : RandomForestClassifier(),
        "params" : {
            "n_estimators" : [1,5,10]
        }
    },
    "logistic_regression" : {
        "model" : LogisticRegression(solver="liblinear",multi_class="auto"),
        "params" : {
            "C" : [1,5,10]
        }
    }
}

In [34]:
scores = []

for model_name , mp in model_params.items():
  clf = GridSearchCV(mp["model"],mp["params"],cv=5,return_train_score=False)
  clf.fit(iris.data,iris.target)
  scores.append({
      "model" : model_name,
      "best_score" : clf.best_score_,
      "best_params" : clf.best_params_
  })

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and wi

In [37]:
df = pd.DataFrame(scores,columns=["model","best_score","best_params"])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.960000        {'n_estimators': 5}
2  logistic_regression    0.966667                   {'C': 5}